### ISSUE TITLE
Can we use this to create actual fonts?

### ISSUE THREAD

**Issue by berkaytheunicorn** [RomanAliyev/figma-export#1]
I wonder if somehow we set up a json file for listing and kerning rules and all other font parameters, can we manage a Figma to real Font solution?

**Comment by rmnli** [comment]
@berkaey,  I suppose not. At the moment, with this package, you can create only iconic (not text) fonts. Probably the real font editor (Fontforge or similar) in your case will be more appropriate than "figma+script+json" solution.
